language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="benchpress:. benchpress-server:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="benchpress" OCAML_VERSION="4.08"
  - PACKAGE="benchpress" OCAML_VERSION="4.10"
  - PACKAGE="benchpress-server" OCAML_VERSION="4.10"
