name: build
on: [push]
jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        ocaml-version: [ '4.08.0' ]
        operating-system: [macos-latest, ubuntu-latest]
        #operating-system: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin -n .
    - run: opam depext -yt benchpress
    - run: opam depext -yt benchpress-server
    - run: opam install -t . --deps-only
    - run: opam exec -- dune build @all --ignore-promoted-rules
    - run: opam exec -- dune runtest --ignore-promoted-rules
